import { NavbarProvider } from "./context/NavbarContext";
import Navbar from "./components/Navbar";
import "./globals.css"; // Tailwind CSS import
import Footer from "./components/Footer";
import { ReactNode } from 'react';

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Sniglet:wght@400;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <NavbarProvider>
          <Navbar />
          <main>{children}</main>
        </NavbarProvider>
        <Footer />
      </body>
    </html>
  );
}
